AWSTemplateFormatVersion: 2010-09-09
Description: "confluence.moussypad.com"
Parameters:
  DomainName:
    Type: String
  HostedZoneId:
    Type: String
  Origin:
    Type: String
Resources:
  ConfluenceRoute:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub confluence.${DomainName}.
      ResourceRecords:
      - !Ref Origin
      TTL: 300
      Type: A